version: '3.8'

services:
  recipes-api:
    build: .
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: db  # Use the service name here
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    # Add restart policy to handle container restarts
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./internal/database/migrations:/docker-entrypoint-initdb.d
    # No need to expose ports here as it's only accessed internally
    # Add restart policy to handle container restarts
    restart: unless-stopped