CREATE TABLE Ingredient (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Quantity FLOAT NOT NULL,
    Unit VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RecipeID INT REFERENCES Recipe(ID) ON DELETE CASCADE
);