CREATE TABLE RecipeCategories (
    ID SERIAL PRIMARY KEY,
    RecipeID INT NOT NULL,
    CategoryID INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RecipeID) REFERENCES Recipe(ID),
    FOREIGN KEY (CategoryID) REFERENCES Category(ID)
);
